# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170628_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
