# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20170628_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/static/product_images'),
        ),
    ]
