# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20171002_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContextTag',
        ),
    ]
