# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20171010_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
