# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_tagaccesshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.SessionTracker'),
        ),
    ]
