# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='name',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
