# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_feedbacks_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='banglarequests',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.ClassTag'),
        ),
        migrations.AlterField(
            model_name='banglaresponses',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.ClassTag'),
        ),
        migrations.AlterField(
            model_name='englishrequests',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.ClassTag'),
        ),
        migrations.AlterField(
            model_name='englishresponses',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.ClassTag'),
        ),
        migrations.AddField(
            model_name='classtag',
            name='agentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Agent'),
        ),
    ]
