# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20171030_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contextClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='chatbot.ClassTag')),
            ],
        ),
        migrations.CreateModel(
            name='ContextMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodName', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='contextMethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.ContextMethod'),
        ),
        migrations.AddField(
            model_name='context',
            name='contextParent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='chatbot.ClassTag'),
        ),
    ]
