# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_auto_20171106_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAccessHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.SessionTracker')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.ClassTag')),
            ],
        ),
    ]
