# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_complaints_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtag',
            name='errorCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
