# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20171001_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banglarequests',
            old_name='request',
            new_name='requestMessage',
        ),
        migrations.RenameField(
            model_name='banglaresponses',
            old_name='response',
            new_name='responseMessage',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='request',
            new_name='requestMessage',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='response',
            new_name='responseMessage',
        ),
        migrations.RenameField(
            model_name='englishrequests',
            old_name='request',
            new_name='requestMessage',
        ),
        migrations.RenameField(
            model_name='englishresponses',
            old_name='response',
            new_name='responseMessage',
        ),
    ]
