# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_delete_contexttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banglarequests',
            name='requestMessage',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='banglaresponses',
            name='responseMessage',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='englishrequests',
            name='requestMessage',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='englishresponses',
            name='responseMessage',
            field=models.CharField(max_length=2000),
        ),
    ]
